name: JS Setup API
description: Setup everything for the API app

inputs:
  node-version:
    description: Node version
    required: false
    default: 18.17.1
  access-token-github:
    description: GitHub token
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
#        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install NodeJS dependencies
      run: |
        cd api
        npm ci
      shell: bash
