version: '3.5'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${GAMESTONK_LOCATION}/volumes/postgres:/var/lib/postgresql/data:rw

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - PORT=${API_PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api/src:/app/src
      - ./api/test:/app/test
      - ./api/node_modules/app/node_modules

# Rappel : https://dev.to/chukwutosin_/step-by-step-guide-setting-up-a-nestjs-application-with-docker-and-postgresql-5hei
  pgadmin:
    image: dpage/pgadmin4
    user: root
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    volumes:
      - ${GAMESTONK_LOCATION}/volumes/pgadmin:/var/lib/pgadmin
    depends_on:
      - db
    
  react:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./front/src:/app/src
      - ./front/public:/app/public
      - ./front/node_modules:/app/node_modules
    depends_on: 
      - api
