FROM node:20-alpine
MAINTAINER Robert Wells <rwells@dvele.com>

WORKDIR /tmp
COPY front/package.json /tmp/

ENV NODE_ENV=development
# RUN npm config set unsafe-perm true

RUN npm install --loglevel verbose
RUN npm i -g typescript tsc-watch nodemon webpack webpack-cli --loglevel verbose

WORKDIR /app

RUN mv /tmp/node_modules /app/node_modules
ENV NODE_PATH=/app/node_modules

# So docker is not being run as a root user
#RUN chown -R node:node /app

COPY /front/package.json /app/
# COPY /front/.eslintrc.json /app/

COPY /front/webpack.config.cjs /app/
COPY /front/tsconfig.json /app/

CMD webpack serve 
