#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# NEEDED BEFORE ALL HOOKS SINCE WE ARE NOT WHERE THE .git DIRECTORY IS
cd front

# TODO: Reactiver quand on aura fini de passer a NestJS
# npm run lint-fix
