# Generated by Django 3.1.12 on 2021-09-29 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stonkapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='itemPriceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonkapi.itemprice'),
        ),
        migrations.AddField(
            model_name='report',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='itemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonkapi.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='itemBankId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stonkapi.itembank'),
        ),
    ]
