# Generated by Django 3.1.12 on 2021-09-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0002_auto_20210929_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembank',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
