# Generated by Django 3.1.12 on 2021-09-29 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stonkapi', '0003_auto_20210929_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyTransactionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_transaction', to='stonkapi.transaction')),
                ('sellTransactionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_transaction', to='stonkapi.transaction')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
