# Generated by Django 3.1.12 on 2021-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0004_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='volume',
            field=models.SmallIntegerField(default=1),
        ),
    ]
