# Generated by Django 3.1.12 on 2021-09-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0006_auto_20210930_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyTransactionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_transaction', to='stonkapi.transaction'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sellTransactionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_transaction', to='stonkapi.transaction'),
        ),
    ]
