# Generated by Django 3.1.12 on 2021-09-29 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stonkapi', '0007_auto_20210930_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
