# Generated by Django 3.1.12 on 2021-09-29 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0009_auto_20210930_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemBankId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stonkapi.itembank'),
        ),
    ]
