# Generated by Django 3.1.12 on 2021-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0011_auto_20210930_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sellOrderPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
