# Generated by Django 3.1.12 on 2021-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0012_trade_sellorderprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='volume',
            field=models.SmallIntegerField(default=1),
        ),
    ]
