# Generated by Django 3.1.12 on 2021-10-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonkapi', '0013_report_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdvBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itembank',
            name='hdv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stonkapi.hdvbank'),
            preserve_default=False,
        ),
    ]
